### ISSUE TITLE
Fields: field type classes

### ISSUE THREAD

**Issue by dillingham** [headlesslaravel/formations#105]
Lets add a field type class feature that is responsible for setting some 

These field classes are used on the frontend to populate vue field components.

The reason this feature will be valuable is that some components will have some complicated setup

And this avoids making the formation class messy with logic.

```php
Field::make('Brand')->as(Picker::class),
```

Basically need to set a $type on the Field class and pass the formation & field to it after all chainable methods are called

Have to figure out when in the lifecycle to "resolve" the field

### Example Field Type

The Picker.vue component is a ajax select component that requires a formation url to get its results

This class sets the component and the vue props of the field to the Picker:

```html
<component :is="field.component" v-bind="field.props"
```

```php
<?php

namespace HeadlessLaravel\Formations\Fields;

use HeadlessLaravel\Formations\Field;
use HeadlessLaravel\Formations\Formation;

class Picker extends FieldType
{
    public function render()
    {
        $this->field->rules(['required']);

        $this->field->component('FieldPicker');

        $this->field->props(['url' => $this->getFormationUrl()]);
    }

    public function getFormationUrl(): string
    {
        return route($this->formation->guessResourceName().'.index');
    }

    public function existsRule()
    {
        $model = app($this->formation->model);

        return "exists:{$model->getTable()},{$model->$this->getKeyName()},"; // exists:users,id
    }
}
```
```php
abstract class FieldType
{
    public $formation;

    public $field;

    public function __construct(Formation $formation, Field $field)
    {
        $this->formation = $formation;

        $this->field = $field;
    }

    public abstract function render();
}
```

Lets add this picker field in the example namespace as its something I think will be useful

More fields will eventually live in that namespace I think

### Testing

To make sure this works, we really only need to call:
```php
Field::make('Brand')->as(Picker::class),
```
And assert its component and rules are as expected in a FieldsTest.php

`test_picker_field_type`

**Comment by mitulgolakiya** [comment]
@dillingham I'm not really vue expert, so was not able to decide when to resolve Field. Also, I'm not sure, how this field will be used on Frontend. Probably because I don't know Inertia.

But check the PR that is kind of near to complete. I just created all classes.

**Comment by dillingham** [comment]
@mitulgolakiya check meta() on formations, it's where all the info is passed to the frontend.
