### ISSUE TITLE
Bulk Actions

### ISSUE THREAD

**Issue by dillingham** [headlesslaravel/formations#17]
### Overview

While formations provides indexes of a model and allows filtering.. it would be very useful to allow using those IDs to trigger queue jobs by adding a method on a formation class that defines actions. That list of actions will be used to define the routes to trigger the actions. Those routes will accept a `selected` request input containing the model ids. The jobs need to be [batched](https://laravel.com/docs/8.x/queues#job-batching) so we can query a action's progress

```php
public function actions()
{
    return [
        Action::make('set-status')
            ->job(SetStatus::class)
            ->can('set-status', Article::class)
            ->fields(['status' => ['in:active,draft'])
            ->after(Event::class),
            ->afterEach(Event::class),
    ];
}
```
### Methods
| method | description |
|---------|------------|
| `job()`   | a queue job that gets called for each item in the results. |
| `can()` | check a gate.. [example ](https://github.com/headlesslaravel/cards/blob/main/src/Card.php#L88-L95) using my cards package.. but then 404 if the route is accessed and is false |
| `after()` | populate an array of things to do after all the jobs are processed |
| `afterEach()` | populate an array of things to do after all the jobs are processed |
| `fields()` | optional values to pass to the job and are validated before the jobs are dispatched |

```php
use \HeadlessLaravel\Formations\Http\Controllers\ActionController;

Route::post("actions/{$formationKey/{$actionKey}", [ActionController::class, 'store'])
    ->name('actions.$actionKey.store');

Route::get("actions/{$formationKey/{$actionKey}/{batchId}", [ActionController::class, 'show'])
    ->name('actions.$actionKey.show');
```
```
POST: actions/articles/set-status
```
which responds with the batch id
```
{
    id: '123456'
}
```
Which allows hitting action endpoint with the id
```
GET: actions/articles/set-status/23423424
```
And getting details about the job.. [here](https://philo.dev/laravel-batches-and-real-time-progress-with-livewire/amp/#:~:text=Eloquent%20models%20and%20database%20migrations) is a nice write up

```php
{
    "status": "complete",
    "total": 5000,
    "worked": 5000,
}
```

```php
<?php

namespace App\Jobs;

use HeadlessLaravel\Formations\Fields;

class SetStatus implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected $article;

    protected $fields;

    public function __construct(Article $article, array $fields)
    {
        $this->article = $article;

        $this->fields = $fields;
    }

    public function handle()
    {
        $this->article->update(['status' => $fields['title]);
    }
}
```

### Parameters

String `all` is all results.. also scoped by the current filters

```php
[ 'selected' => 'all' ]
```
`numeric` is a specific page of the results, IE `?page=3`
```php
[ 'selected' => 3 ]
```
`array` is model IDs. if `ArticleFormation`.. the ids would be `$article->id`s
```php
[ 'selected' => [1,2,3] ]
```

---

```php
->can('setStatus', Article::class)
```
```php

class ArticlePolicy
{
    public function setStatus() {
        return true;
    }
}
```

**Comment by mitulgolakiya** [comment]
@dillingham Please check this WIP PR.

I'm not able to understand the last part of setting up a policy. Can you explain it in a bit more detail?

Also, the `after` and `afterEach` description seems the same, and not sure what to do with that as well.
Do you mean, we should dispatch that event on each successful job processing of batch?

Also, please note that `Bus::fake()` is not persisting `$batchId`, so was not able to write a test for that.

**Comment by dillingham** [comment]
Hey @mitulgolakiya, awesome progress on the actions PR.  Good questions.. that was pretty vague.

### batchId

Ok cool, noted. Can we write a test that does not fake? Like one test that 

- fires the job gets the id from the response
- makes a second request with the id to get the status of the job

### Policies

So the goal here is to allow restricting the access of an action endpoint. So if the developer defines a policy method and calls ->can('method', Model::class).. we should get the policy for that model (example below) and check the outcome of that method. If fails.. the endpoint should [assert forbidden ](https://laravel.com/docs/8.x/http-tests#assert-forbidden) .. 

Lets make the model optional since we know the formation->model.. 

And if they call can(), the policy is not optional like it is in formations controller.. so no if has policy etc

This is how we do it in cards
```php
public function can($ability, $arguments = []): self
{
    $this->allowed = Gate::allows($ability, $arguments);

    return $this;
}
```
And here is how we do it in the base controller for formations

```php
public function check($ability, $arguments = [])
{
    if ($this->hasPolicyMethod($ability)) {
        $this->authorize($ability, $arguments);
    }
}

public function hasPolicyMethod($method): bool
{
    $policy = Gate::getPolicyFor($this->formation()->model);

    return $policy != false && method_exists($policy, $method);
}
```

### Events

Actually now that I think about it, if the developer wants to fire an event.. they can do so in the job

We can skip this

---

Thanks again, this is awesome work

**Comment by mitulgolakiya** [comment]
BatchId stuff is done. Please review this test: https://github.com/InfyOmLabs/formations/blob/af82eacf6ba6ed16b9e9f39e256bda3e4eb369bb/tests/ActionTest.php#L109
