### ISSUE TITLE
Add seeker route prefix

### ISSUE THREAD

**Issue by dillingham** [headlesslaravel/formations#36]
### Overview

For the [global search](https://github.com/headlesslaravel/formations/wiki/Global-Search) feature, a formation guesses a route name to link the search result to. Currently this can be overridden via $detailRouteName

So ProductFormation will guess `products.show`.. 

### The Code
Here is where I register a seeker in the formation [manager](https://github.com/headlesslaravel/formations/blob/main/src/Manager.php#L121-L126)

[Here](https://github.com/headlesslaravel/formations/blob/main/src/Http/Controllers/SeekerController.php#L13) is where I get the formations [stored on the manager class](https://github.com/headlesslaravel/formations/blob/main/src/Manager.php#L121-L126) within the SeekerController

A formation's [seekerMeta()](https://github.com/headlesslaravel/formations/blob/main/src/Formation.php#L420-L438)  is where it guesses the route name

### Problem

This does not take route prefixes into consideration.

Example: `admin.products.show` because all routes within `admin.php` are [prefixed](https://laravel.com/docs/8.x/routing#route-group-prefixes) in a service provider.

I would expect that if I register a global search

```php
Route::seeker('search', [])
```

### Solution

Originally I was thinking to make a config option `formations.seeker.route_prefix`..But Im wondering since we know the prefix at the time of registering the seeker if we can somehow access or store it and use it within the guessing / seeker meta function. 
```php
Route::currentRouteName()

Route::current()->getPrefix()

Route::getLastGroupPrefix()
```

My easy work around was adding `$detailRouteName` but thats more of a work around than a solution

**Comment by mitulgolakiya** [comment]
@dillingham the dynamic route prefix will only work if formation routes and seeker routes are registered under the same prefix. It is also possible that search is prefixed and formation routes are not prefixed.

For example, consider the app where there are two types of users, Admin and User. Where Admin is only allowed to do a global search and user is not. Then routes file may look like the following,

```
Route::prefix('admin')->group(function () {
    Route::seeker('search', [
        PostFormation::class,
        AuthorFormation::class,
    ]);
});

Route::formation('posts', PostFormation::class);
Route::formation('authors', AuthorFormation::class);
Route::formation('authors.posts', PostFormation::class);
Route::formation('posts.tags', TagFormation::class)->pivot();
```

In this case, `posts.show` is still valid. And if we implement to take a prefix of seeker route then it may not work. so I think `$detailRouteName` is the correct solution.

One more thing is, right now we are guessing a resource name from its class name [here](https://github.com/headlesslaravel/formations/blob/main/src/Formation.php#L422).

But what is formation is defined under different route name. Like,

`Route::formation('articles', PostFormation::class);`

The route names in the response meta are still passed as `posts`. we will also need to figure out the solution for this one.

At the moment, I've pushed the fixes to use route prefix if `$detailRouteName` is not defined.

**Comment by dillingham** [comment]
@mitulgolakiya good to know about the prefix being scoped, thank you for that explanation.

I think for the developers who have a need for different route groups, $detailRouteName works

But for the rest of us, it will be nice to not ave to edit a file when we register a seeker.

---

Good catch with the formation name guessing.. that is a bug I agree.

Can we use the "resource" name we register [in the Routes class](https://github.com/headlesslaravel/formations/blob/main/src/Routes.php#L35-L45) from the formation macro

The Manager class is a singleton, which means its the same class used throughout the request.

I did it that way to make the list of resources / formations accessible in controllers etc

I register the formation in the Routes class [here](https://github.com/headlesslaravel/formations/blob/main/src/Routes.php#L135-L144)

```php
app(Manager::class)->formation($this->key)
```

I think that will give you access to the current formation class's resource info
