### ISSUE TITLE
Imports: Add public and private key

### ISSUE THREAD

**Issue by dillingham** [headlesslaravel/formations#53]
```php
Field::make('product_line')
```
```php
Field::make('product_line', 'productLine')
```

Lets replace this work around I added [here](https://github.com/headlesslaravel/formations/pull/54) with a internal key matching [this section](https://github.com/headlesslaravel/formations/blob/main/src/Filter.php#L121-L145) in filter.php.. the first parameter being the public facing key, in filters thats the url parameter, and the internal key being the relationship name.. sometimes they are the same but when the format is different.. the extra parameter is useful.

**Comment by mitulgolakiya** [comment]
@dillingham I was not properly able to understand this, but review this PR and share your thoughts if this is what we want?

https://github.com/headlesslaravel/formations/pull/66

**Comment by dillingham** [comment]
@mitulgolakiya basically it allows the developer to have a different format

```php
Field::make('product_line', 'productLine')
```

means the import file can have `product_line` as the column header

but the model has a `productLine()` relationship

---

In filters we do the same thing.

```php
Filter::make('is_not_paused', 'isActive')->scope()
```

means a public query string parameter `is_not_paused` will collect a value

and will be passed to `isActive` the scope method.

But without both parameters..

```php
Filter::make('active')->scope()
```

This would be `active` the query string parameter and `scopeActive()` the method
