### ISSUE TITLE
Fields: relationship column

### ISSUE THREAD

**Issue by dillingham** [headlesslaravel/formations#61]
Lets change the nested relationship column from
```php
Field::make('author')->relation('name')
```
to dot syntax like other places in the code
```php
Field::make('author.name')->relation()
```

**Comment by mitulgolakiya** [comment]
@dillingham I think with dot syntax support, even if we don't specify `->relation()`, it will still work. so simple,

```
Field::make('author.name');
```

should still work.

**Comment by dillingham** [comment]
@mitulgolakiya thanks for mentioning that.. what way do you personally think is cleaner?

```php
Field::make('author')->related('name')->rules('required'),
Field::make('post_author_name', 'author')->related('name')->rules('required'),
```
```php
Field::make('author.name')->rules('required'),
Field::make('post_author_name', 'author.name')->rules('required'),
```

I guess `relation()` doesn't really need to exist huh? 🤔
