### ISSUE TITLE
Inertia response bug

### ISSUE THREAD

**Issue by dillingham** [headlesslaravel/formations#63]
I un-skipped the tests in #62 to let the tests fail.. hoping we can figure it out

When I run the tests multiple times.. sometimes it passes sometimes it fails.. not sure why.

**Comment by mitulgolakiya** [comment]
@dillingham what I found is, when you run a single test, it's working. But when you run all the tests in a single run it fails.

The reason behind this is, we are getting a wrapped response. Check the below image.

![image](https://user-images.githubusercontent.com/1908535/150075052-3498b614-eb64-41ec-b96d-50e5e4ace1dc.png)

We are calling `$resource::wrap` in Controller.php's [applyResource](https://github.com/headlesslaravel/formations/blob/072712362f382911252f5cd8461c5c10d1c2c22d/src/Http/Controllers/Controller.php#L303) method. This set's a static variable `$wrap` in [JsonResource](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Http/Resources/Json/JsonResource.php#L197).

The default value of `$wrap` is `data`, but in the previous tests, it's modified and then never got reset.

so we will need to come up with some solution where we can reset it after use. One good way is to call [withoutWrapping](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Http/Resources/Json/JsonResource.php#L205). But we need to decide where.

**Comment by mitulgolakiya** [comment]
Check my PR here: https://github.com/headlesslaravel/formations/pull/64

**Comment by dillingham** [comment]
@mitulgolakiya awesome thank you! I was stumped on that for awhile 😆 

Yes it makes sense to unwrap the resource in inertia responses

I haven't tested in blade at all yet in this project.. but we can revisit then
